name: sanity-check

on:
  push:
    branches: [ main ]


jobs:
  Report-Readme:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Read file
        run: cat README.md
