name: test

on:
    push: 
      branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      - run: echo "This is a test workflow"
      - run: echo "Workflow triggered now real checkk"
